### ISSUE TITLE
Set light and dark themes separately and sync it with system

### ISSUE THREAD

**Issue by maicol07** [xpipe-io/xpipe#365]
Add a setting to sync the theme with the system and, when this is enabled, show separate settings for dark/light themes

**Comment by maicol07** [comment]
I confirm it works when XPipe is running. However this won't work:
1. Open XPipe
2. Set system to light
3. Close Xpipe (also close tray)
4. Set system to dark
5. Reopen XPipe
6. Theme is still light

**Comment by crschnick** [comment]
Is that a use case that you have often? I was under the impression that the system theme wasn't changed for most people

**Comment by maicol07** [comment]
I automatically let my system change it at sunrise (basically it changes it when the PC boots the first time in a day) and sunset.
Most times when sunset comes XPipe is opened and the theme changes

**Comment by crschnick** [comment]
Alright I see, I can include that in the next release

**Comment by crschnick** [comment]
This is now implemented in XPipe 13

**Comment by maicol07** [comment]
Hi,

it seems there is an issue with this feature: if you close XPipe with the system dark theme, restart the whole system, change the system theme to light and open XPipe the theme is still dark

**Comment by crschnick** [comment]
Hmm this should work now, at least it does for me in XPipe 13. Can you check the file `<User Home>/.xpipe/cache/lastDarkTheme.cache`, XPipe should write that file on exit with the dark theme state. If that state doesn't match up with the system state on next start, it should change the theme,

**Comment by maicol07** [comment]
It worked with another restart and the file changes! I'll keep it monitored

**Comment by crschnick** [comment]
Is it possible that you may be restarted your system while XPipe was still running? I'm not sure whether it properly shuts down and writes the file when Windows closes running programs on shutdown

**Comment by maicol07** [comment]
Yes, that's very likely

**Comment by khaled-0** [comment]
I still get occasional XPipe stuck in dark mode on macOS.
I always quit xPipe before suspending as far as I remember.

Maybe detecting system theme upon startup would fix that.

**Comment by crschnick** [comment]
@khaled-0 define stuck? Do you change to light theme while xpipe is not running but it still starts up in dark mode?

**Comment by khaled-0** [comment]
> [@khaled-0](https://github.com/khaled-0) define stuck? Do you change to light theme while xpipe is not running but it still starts up in dark mode?

I quit xPipe in dark mode (app & system)
next morning, system in light mode but xpipe opens in dark mode

**Comment by crschnick** [comment]
It will automatically use the system theme if the last theme on exit is different than the one on startup. Was XPipe fully shut down and not set to continue in background?

**Comment by khaled-0** [comment]
> It will automatically use the system theme if the last theme on exit is different than the one on startup. Was XPipe fully shut down and not set to continue in background?

Yes it was. the thing is it only happens sometimes, maybe 5 times out of 50 times, so quite hard to say what exactly is going on.
